#!/bin/bash

echo "🔍 Vercel IDの形式を確認します..."
echo ""
echo "GitHubに設定したIDが以下の形式になっているか確認してください："
echo ""
echo "✅ 正しい形式の例："
echo "=================================="
echo "VERCEL_PROJECT_ID の形式:"
echo "- prj_ で始まる24文字の文字列"
echo "- 例: prj_AbCdEfGhIjKlMnOpQrStUvWx"
echo ""
echo "VERCEL_ORG_ID の形式:"
echo "- team_ で始まる24文字の文字列"
echo "- または: チーム名 (例: shikis-projects-6e27447a)"
echo "- 例: team_1234567890abcdefghijklmn"
echo "=================================="
echo ""
echo "❌ よくある間違い："
echo "- VERCEL_PROJECT_ID に「sms-new」を設定している"
echo "- VERCEL_ORG_ID に「shiki0138」を設定している"
echo "- 前後に余分なスペースが含まれている"
echo "- クォーテーションマークが含まれている"
echo ""
echo "🔧 IDを確認する方法："
echo ""
echo "1. Vercelにログインして実際のIDを確認:"
echo "   https://vercel.com/shikis-projects-6e27447a/sms-new"
echo ""
echo "2. ブラウザでページのソースを表示 (右クリック → ページのソースを表示)"
echo ""
echo "3. ソース内で以下を検索:"
echo "   - \"projectId\" を検索"
echo "   - \"id\":\"prj_ を検索"
echo ""
echo "4. または開発者ツール (F12) のNetworkタブで:"
echo "   - ページをリロード"
echo "   - APIレスポンスを確認"
echo ""
echo "=================================="
echo "📝 別の解決方法："
echo "=================================="
echo ""
echo "もしIDが見つからない場合は、新しいプロジェクトとして"
echo "デプロイしてから、既存のプロジェクトにリンクする方法もあります："
echo ""
echo "# 一時的に別名でデプロイ"
echo "npx vercel --name sms-new-temp"
echo ""
echo "# .vercel/project.json が作成されたら内容を確認"
echo "cat .vercel/project.json"
echo ""
echo "# その後、Vercelダッシュボードで名前を変更"