#!/bin/bash

# Vercel Secrets更新スクリプト
# GitHub Secretsに正しいプロジェクトIDとトークンを設定するためのガイド

echo "🔧 Vercel Secrets 更新ガイド"
echo "================================"
echo ""
echo "📋 必要なシークレット情報:"
echo ""
echo "1. VERCEL_PROJECT_ID:"
echo "   ✅ prj_7b1JDb2Ya215lJk4kfCpE8r2vJkc"
echo ""
echo "2. VERCEL_ORG_ID:"
echo "   - Vercelのダッシュボードで確認してください"
echo "   - https://vercel.com/account"
echo ""
echo "3. VERCEL_TOKEN:"
echo "   - 新しいトークンを生成する必要があります"
echo "   - https://vercel.com/account/tokens"
echo ""
echo "================================"
echo ""
echo "📝 手順:"
echo ""
echo "1. GitHub Secretsページを開く:"
echo "   https://github.com/Shiki0138/sms-new/settings/secrets/actions"
echo ""
echo "2. 以下のシークレットを更新:"
echo ""
echo "   a) VERCEL_PROJECT_ID"
echo "      値: prj_7b1JDb2Ya215lJk4kfCpE8r2vJkc"
echo ""
echo "   b) VERCEL_ORG_ID"
echo "      値: (Vercelダッシュボードから取得)"
echo ""
echo "   c) VERCEL_TOKEN"
echo "      値: (新しく生成したトークン)"
echo ""
echo "================================"
echo ""
echo "🔑 新しいトークンの生成方法:"
echo ""
echo "1. https://vercel.com/account/tokens にアクセス"
echo "2. 'Create' ボタンをクリック"
echo "3. 設定:"
echo "   - Name: github-actions-sms-new-$(date +%Y%m%d)"
echo "   - Scope: Full Account (重要！)"
echo "   - Expiration: No Expiration"
echo "4. トークンをコピー (vercel_xxxxx 形式)"
echo ""
echo "================================"
echo ""
echo "✅ 確認方法:"
echo ""
echo "トークンをテストするには:"
echo "export VERCEL_TOKEN=\"新しいトークン\""
echo "npx vercel whoami"
echo ""
echo "プロジェクト一覧を確認:"
echo "npx vercel projects ls"
echo ""
echo "================================"